CREATE TABLE [dbo].[Requests]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	ClientId int not null,
	CommitteeId int null,
	RequestType tinyint not null default(0),
	BaseRequestId int null,
	Title nvarchar(512) NOT NULL,
	Description nvarchar(max) NULL,
	EarlierStudy nvarchar(max) NULL,
	PopulationDescription nvarchar(max) NULL,
	TherapyDescription nvarchar(max) NULL,
	InternationStudies nvarchar(max) NULL,
	StudyCode nvarchar(20) NULL,
	StudyType int null,
	StudyPhase int not null default(1),
	CentersQty int not null,
	LocalCentersQty int not null default(0),
	PlannedDuration int not null,
	PatientsCount int not null,
	RandomizedPatientsCount int null,
	StudyBase nvarchar(256) NULL,
	StudySponsor nvarchar(256) null,
	StudyProducer nvarchar(256) null,
	StudyPerformer nvarchar(256) null,
	StudyPerformerStatutoryAddress nvarchar(300) null,
	StudyPerformerRegisteredAddress nvarchar(300) null,
	StudyApprovedBy nvarchar(256) null,
	StudyPlannedStartDate datetime null,
	StudyPlannedFinishDate datetime null,
	ContactPerson nvarchar(256) not null,
	ContactPhone nvarchar(20) not null,
	ContactFax nvarchar(20) not null,
	ContactEmail nvarchar(256) not null,
	SubmissionComments nvarchar(1000) null,
	RevokeComments nvarchar(1000) null,
	RejectionComments nvarchar(1000) null,
	LastComments nvarchar(1000) null,
	Created datetime not null default(getutcdate()),
	CreatedBy nvarchar(32) not null,
	SentDate datetime null,
	SubmittedBy nvarchar(32) null,
	Accepted datetime null,
	AcceptedBy nvarchar(32) null,
	Status int not null,

	CONSTRAINT [FK_Request_ToClients] FOREIGN KEY (ClientId) REFERENCES Clients(Id),
	CONSTRAINT [FK_Request_ToCommittees] FOREIGN KEY (CommitteeId) REFERENCES Committees(Id), 
    CONSTRAINT [FK_Request_ToUsers_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [AspNetUsers](UserName),
	CONSTRAINT [FK_Request_ToUsers_AcceptedBy] FOREIGN KEY (AcceptedBy) REFERENCES [AspNetUsers](UserName), 
    CONSTRAINT [FK_Request_ToUsers_SubmittedBy] FOREIGN KEY (SubmittedBy) REFERENCES [AspNetUsers](UserName), 
    CONSTRAINT [FK_Request_ToRequests_BaseRequestId] FOREIGN KEY (BaseRequestId) REFERENCES [Requests](Id), 
    CONSTRAINT [CK_Request_CentersQty] CHECK (CentersQty >= 1),
)
