//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecOnline.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LecOnline.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять.
        /// </summary>
        public static string ActionAccept {
            get {
                return ResourceManager.GetString("ActionAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буду участвовать.
        /// </summary>
        public static string ActionAcceptMeeting {
            get {
                return ResourceManager.GetString("ActionAcceptMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активировать.
        /// </summary>
        public static string ActionActivate {
            get {
                return ResourceManager.GetString("ActionActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление.
        /// </summary>
        public static string ActionCreateNotification {
            get {
                return ResourceManager.GetString("ActionCreateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вторичная подача.
        /// </summary>
        public static string ActionCreateSecondary {
            get {
                return ResourceManager.GetString("ActionCreateSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деактивировать.
        /// </summary>
        public static string ActionDeactivate {
            get {
                return ResourceManager.GetString("ActionDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не буду участвовать.
        /// </summary>
        public static string ActionDeclineMeeting {
            get {
                return ResourceManager.GetString("ActionDeclineMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее.
        /// </summary>
        public static string ActionDetails {
            get {
                return ResourceManager.GetString("ActionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string ActionEdit {
            get {
                return ResourceManager.GetString("ActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вынести решение.
        /// </summary>
        public static string ActionEnterMeetingResolution {
            get {
                return ResourceManager.GetString("ActionEnterMeetingResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить совещание.
        /// </summary>
        public static string ActionFinishMeeting {
            get {
                return ResourceManager.GetString("ActionFinishMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Совещание.
        /// </summary>
        public static string ActionMeetingRoom {
            get {
                return ResourceManager.GetString("ActionMeetingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс пароля.
        /// </summary>
        public static string ActionPasswordReset {
            get {
                return ResourceManager.GetString("ActionPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отклонить.
        /// </summary>
        public static string ActionReject {
            get {
                return ResourceManager.GetString("ActionReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отозвать.
        /// </summary>
        public static string ActionRevoke {
            get {
                return ResourceManager.GetString("ActionRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначить совещание.
        /// </summary>
        public static string ActionSetMeeting {
            get {
                return ResourceManager.GetString("ActionSetMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать совещание.
        /// </summary>
        public static string ActionStartMeeting {
            get {
                return ResourceManager.GetString("ActionStartMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать голосование.
        /// </summary>
        public static string ActionStartVoting {
            get {
                return ResourceManager.GetString("ActionStartVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить совещание.
        /// </summary>
        public static string ActionStopMeeting {
            get {
                return ResourceManager.GetString("ActionStopMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подать заявку.
        /// </summary>
        public static string ActionSubmit {
            get {
                return ResourceManager.GetString("ActionSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участники.
        /// </summary>
        public static string ActionViewAttendees {
            get {
                return ResourceManager.GetString("ActionViewAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История.
        /// </summary>
        public static string ActionViewRequestHistory {
            get {
                return ResourceManager.GetString("ActionViewRequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка отправки email.
        /// </summary>
        public static string MailErrorFailedToSendEmail {
            get {
                return ResourceManager.GetString("MailErrorFailedToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для заявки &apos;{0}&apos; назначено совещание.
        ///
        ///Дата проведения: {1:d}
        ///Время проведения: {1:t}
        ///Ссылка: {2}.
        /// </summary>
        public static string MailMeetingSetupBody {
            get {
                return ResourceManager.GetString("MailMeetingSetupBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначено совещание.
        /// </summary>
        public static string MailMeetingSetupSubject {
            get {
                return ResourceManager.GetString("MailMeetingSetupSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическая система уведомлений.
        /// </summary>
        public static string MailNoReplyUser {
            get {
                return ResourceManager.GetString("MailNoReplyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос &apos;{0}&apos; принят на рассмотрение..
        /// </summary>
        public static string MailRequestAcceptedBody {
            get {
                return ResourceManager.GetString("MailRequestAcceptedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш запрос принят.
        /// </summary>
        public static string MailRequestAcceptedSubject {
            get {
                return ResourceManager.GetString("MailRequestAcceptedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос &apos;{0}&apos; отклонен.
        ///
        ///Причина отклонения: {1}.
        /// </summary>
        public static string MailRequestRejectedBody {
            get {
                return ResourceManager.GetString("MailRequestRejectedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш запрос отклонен.
        /// </summary>
        public static string MailRequestRejectedSubject {
            get {
                return ResourceManager.GetString("MailRequestRejectedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша заявка &apos;{0}&apos; была обработана.
        ///
        ///Решение комитета: {1}
        ///Узнать подробную информацию и скачать решение комитета вы можете по ссылке {2}.
        /// </summary>
        public static string MailRequestResolutionMadeBody {
            get {
                return ResourceManager.GetString("MailRequestResolutionMadeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Решение по заявке.
        /// </summary>
        public static string MailRequestResolutionMadeSubject {
            get {
                return ResourceManager.GetString("MailRequestResolutionMadeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получена новая заявка &apos;{0}&apos;.
        /// </summary>
        public static string MailRequestSubmittedBody {
            get {
                return ResourceManager.GetString("MailRequestSubmittedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получена новая заявка.
        /// </summary>
        public static string MailRequestSubmittedSubject {
            get {
                return ResourceManager.GetString("MailRequestSubmittedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Началось голосование:
        ///Совещание №{0} по заявке №{1}, &apos;{2}&apos;.
        /// </summary>
        public static string MeetingVotingStarted {
            get {
                return ResourceManager.GetString("MeetingVotingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос принят к обработке: 
        ///{0}.
        /// </summary>
        public static string RequestAccepted {
            get {
                return ResourceManager.GetString("RequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные о заявке изменены: 
        ///{0}.
        /// </summary>
        public static string RequestChanged {
            get {
                return ResourceManager.GetString("RequestChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлены данные о заявке: 
        ///{0}.
        /// </summary>
        public static string RequestCreated {
            get {
                return ResourceManager.GetString("RequestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные о заявке удалены,прошлые данные о заявке до удаления: 
        ///{0}.
        /// </summary>
        public static string RequestDeleted {
            get {
                return ResourceManager.GetString("RequestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружена документация:
        ///Заявка №{0}, &apos;{1}&apos;
        ///{2}.
        /// </summary>
        public static string RequestDocumentationCreated {
            get {
                return ResourceManager.GetString("RequestDocumentationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалена документация:
        ///Заявка №{0}, &apos;{1}&apos;
        ///{2}.
        /// </summary>
        public static string RequestDocumentationDeleted {
            get {
                return ResourceManager.GetString("RequestDocumentationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос отклонен: 
        ///{0}.
        /// </summary>
        public static string RequestRejected {
            get {
                return ResourceManager.GetString("RequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос отозван: 
        ///{0}.
        /// </summary>
        public static string RequestRevoked {
            get {
                return ResourceManager.GetString("RequestRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос отправлен в ЛЭК: 
        ///{0}.
        /// </summary>
        public static string RequestSubmitted {
            get {
                return ResourceManager.GetString("RequestSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кабинет.
        /// </summary>
        public static string SidebarDashboard {
            get {
                return ResourceManager.GetString("SidebarDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Медцентры.
        /// </summary>
        public static string SidebarMedicalCenters {
            get {
                return ResourceManager.GetString("SidebarMedicalCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявки.
        /// </summary>
        public static string SidebarRequests {
            get {
                return ResourceManager.GetString("SidebarRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Безопасность.
        /// </summary>
        public static string SidebarSecurity {
            get {
                return ResourceManager.GetString("SidebarSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string SidebarSettings {
            get {
                return ResourceManager.GetString("SidebarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string SidebarUsers {
            get {
                return ResourceManager.GetString("SidebarUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исследование разрешено.
        /// </summary>
        public static string StudyAccepted {
            get {
                return ResourceManager.GetString("StudyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исследование отклонено.
        /// </summary>
        public static string StudyRejected {
            get {
                return ResourceManager.GetString("StudyRejected", resourceCulture);
            }
        }
    }
}
