//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecOnline.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Committee
    {
        public Committee()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string Chairman { get; set; }
        public string Secretary { get; set; }
        public string ViceChairman { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
