//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecOnline.Core
{
    
    
    /// <summary>
    /// The LecOnlineConfigurationSection Configuration Section.
    /// </summary>
    public partial class LecOnlineConfigurationSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the LecOnlineConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string LecOnlineConfigurationSectionSectionName = "lecOnline";
        
        /// <summary>
        /// The XML path of the LecOnlineConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string LecOnlineConfigurationSectionSectionPath = "lecOnline";
        
        /// <summary>
        /// Gets the LecOnlineConfigurationSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public static global::LecOnline.Core.LecOnlineConfigurationSection Instance
        {
            get
            {
                return ((global::LecOnline.Core.LecOnlineConfigurationSection)(global::System.Configuration.ConfigurationManager.GetSection(global::LecOnline.Core.LecOnlineConfigurationSection.LecOnlineConfigurationSectionSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::LecOnline.Core.LecOnlineConfigurationSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::LecOnline.Core.LecOnlineConfigurationSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Phone Property
        /// <summary>
        /// The XML name of the <see cref="Phone"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string PhonePropertyName = "phone";
        
        /// <summary>
        /// Gets or sets company phone
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("Company phone")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::LecOnline.Core.LecOnlineConfigurationSection.PhonePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Phone
        {
            get
            {
                return ((string)(base[global::LecOnline.Core.LecOnlineConfigurationSection.PhonePropertyName]));
            }
            set
            {
                base[global::LecOnline.Core.LecOnlineConfigurationSection.PhonePropertyName] = value;
            }
        }
        #endregion
        
        #region Email Property
        /// <summary>
        /// The XML name of the <see cref="Email"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string EmailPropertyName = "email";
        
        /// <summary>
        /// Gets or sets email for the website
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("Email for the website")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::LecOnline.Core.LecOnlineConfigurationSection.EmailPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Email
        {
            get
            {
                return ((string)(base[global::LecOnline.Core.LecOnlineConfigurationSection.EmailPropertyName]));
            }
            set
            {
                base[global::LecOnline.Core.LecOnlineConfigurationSection.EmailPropertyName] = value;
            }
        }
        #endregion
        
        #region Skype Property
        /// <summary>
        /// The XML name of the <see cref="Skype"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SkypePropertyName = "skype";
        
        /// <summary>
        /// Gets or sets name of the Skype account which will be used for the communication
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("Name of the Skype account which will be used for the communication")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::LecOnline.Core.LecOnlineConfigurationSection.SkypePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Skype
        {
            get
            {
                return ((string)(base[global::LecOnline.Core.LecOnlineConfigurationSection.SkypePropertyName]));
            }
            set
            {
                base[global::LecOnline.Core.LecOnlineConfigurationSection.SkypePropertyName] = value;
            }
        }
        #endregion
        
        #region NoReplyAddress Property
        /// <summary>
        /// The XML name of the <see cref="NoReplyAddress"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string NoReplyAddressPropertyName = "noReplyAddress";
        
        /// <summary>
        /// Gets or sets the NoReplyAddress.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The NoReplyAddress.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::LecOnline.Core.LecOnlineConfigurationSection.NoReplyAddressPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string NoReplyAddress
        {
            get
            {
                return ((string)(base[global::LecOnline.Core.LecOnlineConfigurationSection.NoReplyAddressPropertyName]));
            }
            set
            {
                base[global::LecOnline.Core.LecOnlineConfigurationSection.NoReplyAddressPropertyName] = value;
            }
        }
        #endregion
        
        #region SendNotificationEmails Property
        /// <summary>
        /// The XML name of the <see cref="SendNotificationEmails"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SendNotificationEmailsPropertyName = "sendNotificationEmails";
        
        /// <summary>
        /// Gets or sets the SendNotificationEmails.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The SendNotificationEmails.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::LecOnline.Core.LecOnlineConfigurationSection.SendNotificationEmailsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=false)]
        public virtual bool SendNotificationEmails
        {
            get
            {
                return ((bool)(base[global::LecOnline.Core.LecOnlineConfigurationSection.SendNotificationEmailsPropertyName]));
            }
            set
            {
                base[global::LecOnline.Core.LecOnlineConfigurationSection.SendNotificationEmailsPropertyName] = value;
            }
        }
        #endregion
    }
}
