//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecOnline.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LecOnlineDbEntities : DbContext
    {
        public LecOnlineDbEntities()
            : base("name=LecOnlineDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Committee> Committees { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<RequestDocumentation> RequestDocumentations { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<MeetingAttendee> MeetingAttendees { get; set; }
        public virtual DbSet<ChangesLog> ChangesLogs { get; set; }
        public virtual DbSet<MeetingChatMessage> MeetingChatMessages { get; set; }
        public virtual DbSet<RequestAction> RequestActions { get; set; }
    }
}
