//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecOnline.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.MeetingAttendees = new HashSet<MeetingAttendee>();
            this.MeetingChatMessages = new HashSet<MeetingChatMessage>();
        }
    
        public int Id { get; set; }
        public int RequestId { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public string Protocol { get; set; }
        public string MeetingLog { get; set; }
        public int Status { get; set; }
        public int Resolution { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual ICollection<MeetingAttendee> MeetingAttendees { get; set; }
        public virtual ICollection<MeetingChatMessage> MeetingChatMessages { get; set; }
    }
}
