//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecOnline.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Meetings = new HashSet<Meeting>();
            this.RequestDocumentations = new HashSet<RequestDocumentation>();
            this.RequestActions = new HashSet<RequestAction>();
            this.SubsequentRequests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> CommitteeId { get; set; }
        public string Title { get; set; }
        public string StudyCode { get; set; }
        public Nullable<int> StudyType { get; set; }
        public int CentersQty { get; set; }
        public int PlannedDuration { get; set; }
        public int PatientsCount { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactEmail { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> Accepted { get; set; }
        public string AcceptedBy { get; set; }
        public int Status { get; set; }
        public string SubmissionComments { get; set; }
        public string RevokeComments { get; set; }
        public string RejectionComments { get; set; }
        public string LastComments { get; set; }
        public Nullable<int> RandomizedPatientsCount { get; set; }
        public string StudySponsor { get; set; }
        public string StudyProducer { get; set; }
        public string StudyPerformer { get; set; }
        public string StudyPerformerStatutoryAddress { get; set; }
        public string StudyPerformerRegisteredAddress { get; set; }
        public string StudyApprovedBy { get; set; }
        public string Description { get; set; }
        public string StudyBase { get; set; }
        public int StudyPhase { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> StudyPlannedStartDate { get; set; }
        public Nullable<System.DateTime> StudyPlannedFinishDate { get; set; }
        public string EarlierStudy { get; set; }
        public string PopulationDescription { get; set; }
        public string TherapyDescription { get; set; }
        public string InternationStudies { get; set; }
        public int LocalCentersQty { get; set; }
        public byte RequestType { get; set; }
        public Nullable<int> BaseRequestId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Committee Committee { get; set; }
        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual ICollection<RequestDocumentation> RequestDocumentations { get; set; }
        public virtual ICollection<RequestAction> RequestActions { get; set; }
        public virtual ICollection<Request> SubsequentRequests { get; set; }
        public virtual Request BaseRequest { get; set; }
    }
}
