//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecOnline.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestAction
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public byte ActionType { get; set; }
        public string Description { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string UserName { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
