//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecOnline.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDocumentation
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public string Name { get; set; }
        public byte[] Content { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Signed { get; set; }
        public string SignedBy { get; set; }
        public byte FileType { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
