//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecOnline.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LecOnline.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воздержался.
        /// </summary>
        public static string Abstain {
            get {
                return ResourceManager.GetString("Abstain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша учетная запись заблокирована, попробуйте повторить попытку.
        /// </summary>
        public static string AccountLockedOut {
            get {
                return ResourceManager.GetString("AccountLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад в кабинет.
        /// </summary>
        public static string BackToDashboard {
            get {
                return ResourceManager.GetString("BackToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад к редактированию.
        /// </summary>
        public static string BackToEdit {
            get {
                return ResourceManager.GetString("BackToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад к списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад к входу.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить загрузку.
        /// </summary>
        public static string CancelUpload {
            get {
                return ResourceManager.GetString("CancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите отменить загрузку файла..
        /// </summary>
        public static string CancelUploadConfirmation {
            get {
                return ResourceManager.GetString("CancelUploadConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измените ваш пароль.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите роль ....
        /// </summary>
        public static string ChooseUserRole {
            get {
                return ResourceManager.GetString("ChooseUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание клиента.
        /// </summary>
        public static string CreateClient {
            get {
                return ResourceManager.GetString("CreateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание комитета.
        /// </summary>
        public static string CreateCommittee {
            get {
                return ResourceManager.GetString("CreateCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое уведомление.
        /// </summary>
        public static string CreateNotificationRequest {
            get {
                return ResourceManager.GetString("CreateNotificationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить пароль.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая заявка.
        /// </summary>
        public static string CreateRequest {
            get {
                return ResourceManager.GetString("CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вторичная подача.
        /// </summary>
        public static string CreateSecondaryRequest {
            get {
                return ResourceManager.GetString("CreateSecondaryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать пользователя.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить эту запись?.
        /// </summary>
        public static string DeletePrompt {
            get {
                return ResourceManager.GetString("DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление заявки.
        /// </summary>
        public static string DeleteRequest {
            get {
                return ResourceManager.GetString("DeleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить документацию.
        /// </summary>
        public static string DeleteRequestDocumentation {
            get {
                return ResourceManager.GetString("DeleteRequestDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архив документации.
        /// </summary>
        public static string DocumentationAttachment {
            get {
                return ResourceManager.GetString("DocumentationAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка.
        /// </summary>
        public static string DocumentationRequest {
            get {
                return ResourceManager.GetString("DocumentationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выписка.
        /// </summary>
        public static string DocumentationResolution {
            get {
                return ResourceManager.GetString("DocumentationResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перетяните файлы.
        /// </summary>
        public static string DropzoneDropFiles {
            get {
                return ResourceManager.GetString("DropzoneDropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на или нажмите мышкой.
        /// </summary>
        public static string DropzoneOrClick {
            get {
                return ResourceManager.GetString("DropzoneOrClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на для загрузки.
        /// </summary>
        public static string DropzoneToUpload {
            get {
                return ResourceManager.GetString("DropzoneToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование клиента.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование комитета.
        /// </summary>
        public static string EditCommittee {
            get {
                return ResourceManager.GetString("EditCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование заявки.
        /// </summary>
        public static string EditRequest {
            get {
                return ResourceManager.GetString("EditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование пользователя.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ваши данные.
        /// </summary>
        public static string EnterUsingLocalAccount {
            get {
                return ResourceManager.GetString("EnterUsingLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассмотрено.
        /// </summary>
        public static string FieldAcceptedBy {
            get {
                return ResourceManager.GetString("FieldAcceptedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рассмотрения.
        /// </summary>
        public static string FieldAcceptedDate {
            get {
                return ResourceManager.GetString("FieldAcceptedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string FieldActionDate {
            get {
                return ResourceManager.GetString("FieldActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string FieldActionDescription {
            get {
                return ResourceManager.GetString("FieldActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string FieldActionUser {
            get {
                return ResourceManager.GetString("FieldActionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string FieldAddress {
            get {
                return ResourceManager.GetString("FieldAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество исследовательских центров.
        /// </summary>
        public static string FieldCentersQty {
            get {
                return ResourceManager.GetString("FieldCentersQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Председатель.
        /// </summary>
        public static string FieldChairman {
            get {
                return ResourceManager.GetString("FieldChairman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменивший пользователь.
        /// </summary>
        public static string FieldChangedBy {
            get {
                return ResourceManager.GetString("FieldChangedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата изменения.
        /// </summary>
        public static string FieldChangedDate {
            get {
                return ResourceManager.GetString("FieldChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание изменений.
        /// </summary>
        public static string FieldChangeDescription {
            get {
                return ResourceManager.GetString("FieldChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        public static string FieldCity {
            get {
                return ResourceManager.GetString("FieldCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент.
        /// </summary>
        public static string FieldClient {
            get {
                return ResourceManager.GetString("FieldClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string FieldCode {
            get {
                return ResourceManager.GetString("FieldCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комитет.
        /// </summary>
        public static string FieldCommittee {
            get {
                return ResourceManager.GetString("FieldCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания.
        /// </summary>
        public static string FieldCompany {
            get {
                return ResourceManager.GetString("FieldCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название компании.
        /// </summary>
        public static string FieldCompanyName {
            get {
                return ResourceManager.GetString("FieldCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите пароль.
        /// </summary>
        public static string FieldConfirmPassword {
            get {
                return ResourceManager.GetString("FieldConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактное лицо.
        /// </summary>
        public static string FieldContactPerson {
            get {
                return ResourceManager.GetString("FieldContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить редактирование заявки после ее создания?.
        /// </summary>
        public static string FieldContinuteToEditPage {
            get {
                return ResourceManager.GetString("FieldContinuteToEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создано.
        /// </summary>
        public static string FieldCreatedBy {
            get {
                return ResourceManager.GetString("FieldCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата создания.
        /// </summary>
        public static string FieldCreatedDate {
            get {
                return ResourceManager.GetString("FieldCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Научная степень.
        /// </summary>
        public static string FieldDegree {
            get {
                return ResourceManager.GetString("FieldDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цель клинического исследования.
        /// </summary>
        public static string FieldDescription {
            get {
                return ResourceManager.GetString("FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документы.
        /// </summary>
        public static string FieldDocumentation {
            get {
                return ResourceManager.GetString("FieldDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ранее проводимые исследования.
        /// </summary>
        public static string FieldEarlierStudy {
            get {
                return ResourceManager.GetString("FieldEarlierStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string FieldEmail {
            get {
                return ResourceManager.GetString("FieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Факс.
        /// </summary>
        public static string FieldFax {
            get {
                return ResourceManager.GetString("FieldFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла.
        /// </summary>
        public static string FieldFileName {
            get {
                return ResourceManager.GetString("FieldFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string FieldFirstName {
            get {
                return ResourceManager.GetString("FieldFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное имя.
        /// </summary>
        public static string FieldFullName {
            get {
                return ResourceManager.GetString("FieldFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string FieldId {
            get {
                return ResourceManager.GetString("FieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Международное участие.
        /// </summary>
        public static string FieldInternationStudies {
            get {
                return ResourceManager.GetString("FieldInternationStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string FieldLastName {
            get {
                return ResourceManager.GetString("FieldLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во центров в РФ.
        /// </summary>
        public static string FieldLocalCentersQty {
            get {
                return ResourceManager.GetString("FieldLocalCentersQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата совещания.
        /// </summary>
        public static string FieldMeetingDate {
            get {
                return ResourceManager.GetString("FieldMeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол заседания.
        /// </summary>
        public static string FieldMeetingLog {
            get {
                return ResourceManager.GetString("FieldMeetingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участники.
        /// </summary>
        public static string FieldMembers {
            get {
                return ResourceManager.GetString("FieldMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        public static string FieldMessage {
            get {
                return ResourceManager.GetString("FieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата изменения.
        /// </summary>
        public static string FieldModifiedDate {
            get {
                return ResourceManager.GetString("FieldModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заметки.
        /// </summary>
        public static string FieldNotes {
            get {
                return ResourceManager.GetString("FieldNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код объекта.
        /// </summary>
        public static string FieldObjectId {
            get {
                return ResourceManager.GetString("FieldObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип объекта.
        /// </summary>
        public static string FieldObjectType {
            get {
                return ResourceManager.GetString("FieldObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string FieldPassword {
            get {
                return ResourceManager.GetString("FieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скринированные.
        /// </summary>
        public static string FieldPatientsCount {
            get {
                return ResourceManager.GetString("FieldPatientsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string FieldPatronymicName {
            get {
                return ResourceManager.GetString("FieldPatronymicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string FieldPhone {
            get {
                return ResourceManager.GetString("FieldPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на План. длит. участия пациентов (нед.).
        /// </summary>
        public static string FieldPlannedDuration {
            get {
                return ResourceManager.GetString("FieldPlannedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание популяции.
        /// </summary>
        public static string FieldPopulationDescription {
            get {
                return ResourceManager.GetString("FieldPopulationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принятое решение.
        /// </summary>
        public static string FieldProtocol {
            get {
                return ResourceManager.GetString("FieldProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рандомизированных.
        /// </summary>
        public static string FieldRandomizedPatientsCount {
            get {
                return ResourceManager.GetString("FieldRandomizedPatientsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причины отказа в обработке заявки.
        /// </summary>
        public static string FieldRejectionReason {
            get {
                return ResourceManager.GetString("FieldRejectionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить меня?.
        /// </summary>
        public static string FieldRememberMe {
            get {
                return ResourceManager.GetString("FieldRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить данный браузер?.
        /// </summary>
        public static string FieldRememberThisBrowser {
            get {
                return ResourceManager.GetString("FieldRememberThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Решение.
        /// </summary>
        public static string FieldResolution {
            get {
                return ResourceManager.GetString("FieldResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причины отзыва заявки.
        /// </summary>
        public static string FieldRevocationComment {
            get {
                return ResourceManager.GetString("FieldRevocationComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роли.
        /// </summary>
        public static string FieldRoles {
            get {
                return ResourceManager.GetString("FieldRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Секретарь.
        /// </summary>
        public static string FieldSecretary {
            get {
                return ResourceManager.GetString("FieldSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите комитет куда отправить заявку.
        /// </summary>
        public static string FieldSelectCommitteeForSubmission {
            get {
                return ResourceManager.GetString("FieldSelectCommitteeForSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string FieldStatus {
            get {
                return ResourceManager.GetString("FieldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № приказа МЗ РФ.
        /// </summary>
        public static string FieldStudyApprovedBy {
            get {
                return ResourceManager.GetString("FieldStudyApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испытательная база.
        /// </summary>
        public static string FieldStudyBase {
            get {
                return ResourceManager.GetString("FieldStudyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер протокола.
        /// </summary>
        public static string FieldStudyCode {
            get {
                return ResourceManager.GetString("FieldStudyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания проводящая исследование.
        /// </summary>
        public static string FieldStudyPerformer {
            get {
                return ResourceManager.GetString("FieldStudyPerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юридический адрес.
        /// </summary>
        public static string FieldStudyPerformerRegisteredAddress {
            get {
                return ResourceManager.GetString("FieldStudyPerformerRegisteredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактический адрес.
        /// </summary>
        public static string FieldStudyPerformerStatutoryAddress {
            get {
                return ResourceManager.GetString("FieldStudyPerformerStatutoryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза исследования.
        /// </summary>
        public static string FieldStudyPhase {
            get {
                return ResourceManager.GetString("FieldStudyPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания исследования..
        /// </summary>
        public static string FieldStudyPlannedEndDate {
            get {
                return ResourceManager.GetString("FieldStudyPlannedEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала иссл..
        /// </summary>
        public static string FieldStudyPlannedStartDate {
            get {
                return ResourceManager.GetString("FieldStudyPlannedStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производитель/упаковщик.
        /// </summary>
        public static string FieldStudyProducer {
            get {
                return ResourceManager.GetString("FieldStudyProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спонсор исследования.
        /// </summary>
        public static string FieldStudySponsor {
            get {
                return ResourceManager.GetString("FieldStudySponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название исследования.
        /// </summary>
        public static string FieldStudyTitle {
            get {
                return ResourceManager.GetString("FieldStudyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип исследования.
        /// </summary>
        public static string FieldStudyType {
            get {
                return ResourceManager.GetString("FieldStudyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коментарии для коммиссии.
        /// </summary>
        public static string FieldSubmissionComment {
            get {
                return ResourceManager.GetString("FieldSubmissionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подать с не полным пакетом документов.
        /// </summary>
        public static string FieldSuppressMissingFiles {
            get {
                return ResourceManager.GetString("FieldSuppressMissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подход к терапии лечения.
        /// </summary>
        public static string FieldTherapyDescription {
            get {
                return ResourceManager.GetString("FieldTherapyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string FieldTitle {
            get {
                return ResourceManager.GetString("FieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двух-факторная аутентификация.
        /// </summary>
        public static string FieldTwoFactorAuthentication {
            get {
                return ResourceManager.GetString("FieldTwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string FieldUserName {
            get {
                return ResourceManager.GetString("FieldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зам. председателя.
        /// </summary>
        public static string FieldViceChairman {
            get {
                return ResourceManager.GetString("FieldViceChairman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голос.
        /// </summary>
        public static string FieldVote {
            get {
                return ResourceManager.GetString("FieldVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешение от министерства РФ.
        /// </summary>
        public static string FileAllowanceFromMinistryOfHealth {
            get {
                return ResourceManager.GetString("FileAllowanceFromMinistryOfHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешение от министерства РФ отсутсвует.
        /// </summary>
        public static string FileAllowanceFromMinistryOfHealthIsMissing {
            get {
                return ResourceManager.GetString("FileAllowanceFromMinistryOfHealthIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выписка из протокола по этике.
        /// </summary>
        public static string FileExcerptFromEthicsProtocol {
            get {
                return ResourceManager.GetString("FileExcerptFromEthicsProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выписка из протокола по этике отсутсвует.
        /// </summary>
        public static string FileExcerptFromEthicsProtocolIsMissing {
            get {
                return ResourceManager.GetString("FileExcerptFromEthicsProtocolIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма информированного согласия.
        /// </summary>
        public static string FileInformedAgreementForm {
            get {
                return ResourceManager.GetString("FileInformedAgreementForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма информированного согласия отсуствует.
        /// </summary>
        public static string FileInformedAgreementFormIsMissing {
            get {
                return ResourceManager.GetString("FileInformedAgreementFormIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брошюра иследователя по препарату.
        /// </summary>
        public static string FileResearchBrochure {
            get {
                return ResourceManager.GetString("FileResearchBrochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брошюра иследователя по препарату отсутсвует.
        /// </summary>
        public static string FileResearchBrochureIsMissing {
            get {
                return ResourceManager.GetString("FileResearchBrochureIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол клинического исследования.
        /// </summary>
        public static string FileStudyProtocol {
            get {
                return ResourceManager.GetString("FileStudyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол клинического исследования отсутсвует.
        /// </summary>
        public static string FileStudyProtocolIsMissing {
            get {
                return ResourceManager.GetString("FileStudyProtocolIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл слишком большой.
        /// </summary>
        public static string FileTooBig {
            get {
                return ResourceManager.GetString("FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От.
        /// </summary>
        public static string FilterFromDate {
            get {
                return ResourceManager.GetString("FilterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string FilterRequestName {
            get {
                return ResourceManager.GetString("FilterRequestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string FilterRequestStatus {
            get {
                return ResourceManager.GetString("FilterRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До.
        /// </summary>
        public static string FilterTillDate {
            get {
                return ResourceManager.GetString("FilterTillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент.
        /// </summary>
        public static string FilterUserClient {
            get {
                return ResourceManager.GetString("FilterUserClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комитет.
        /// </summary>
        public static string FilterUserCommittee {
            get {
                return ResourceManager.GetString("FilterUserCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string FilterUserName {
            get {
                return ResourceManager.GetString("FilterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забыли пароль?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка файлов не завершена. Дождитесь завершения загрузки, или отмените загрузку файлов чтобы закрыть окно.
        /// </summary>
        public static string HasFilesPendingUpload {
            get {
                return ResourceManager.GetString("HasFilesPendingUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите ранее проводимые исследования с данным препаратом. Это поможет сотрудникам комитета иметь более полное представление о препарате..
        /// </summary>
        public static string HelpEarlierStudy {
            get {
                return ResourceManager.GetString("HelpEarlierStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите другие международные исследования с данным препаратом, если это применимо..
        /// </summary>
        public static string HelpInternationStudies {
            get {
                return ResourceManager.GetString("HelpInternationStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое перечисление событий произошедших на совещании.
        /// </summary>
        public static string HelpMeetingLog {
            get {
                return ResourceManager.GetString("HelpMeetingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите описание популяции, с которой будет проводится исследование. .
        /// </summary>
        public static string HelpPopulationDescription {
            get {
                return ResourceManager.GetString("HelpPopulationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string HelpPopupHeader {
            get {
                return ResourceManager.GetString("HelpPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перечисление принятых на митинге решений в текстовой форме.
        ///Данный текст попадет в выписку.
        /// </summary>
        public static string HelpProtocol {
            get {
                return ResourceManager.GetString("HelpProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое описание решения по заявке принятое на митинге..
        /// </summary>
        public static string HelpResolution {
            get {
                return ResourceManager.GetString("HelpResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите кол-во центров в которых будет проводиться исследование.
        /// </summary>
        public static string HelpTextCentersQty {
            get {
                return ResourceManager.GetString("HelpTextCentersQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опишите цель клинического исследования в соотвествии с ФЗ &quot;Об обращении лекарственных средств&quot;.
        /// </summary>
        public static string HelpTextDescription {
            get {
                return ResourceManager.GetString("HelpTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество исследовательских центров в РФ.
        /// </summary>
        public static string HelpTextLocalCentersQty {
            get {
                return ResourceManager.GetString("HelpTextLocalCentersQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите планируемое количество пациентов.
        /// </summary>
        public static string HelpTextPatientsCount {
            get {
                return ResourceManager.GetString("HelpTextPatientsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите планируемую длительность клинического исследования в неделях.
        /// </summary>
        public static string HelpTextPlannedDuration {
            get {
                return ResourceManager.GetString("HelpTextPlannedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите планируемое количество пациентов котороые будут рандомизированы в рамках проводимого испытания.
        /// </summary>
        public static string HelpTextRandomizedPatientsCount {
            get {
                return ResourceManager.GetString("HelpTextRandomizedPatientsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите документ МЗ РФ который одобрил проведение данного клинического исследования.
        /// </summary>
        public static string HelpTextStudyApprovedBy {
            get {
                return ResourceManager.GetString("HelpTextStudyApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учреждение где будет проводиться испытание.
        /// </summary>
        public static string HelpTextStudyBase {
            get {
                return ResourceManager.GetString("HelpTextStudyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код проводимого исследования.
        /// </summary>
        public static string HelpTextStudyCode {
            get {
                return ResourceManager.GetString("HelpTextStudyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите компанию которая проводит клиническое исследование.
        /// </summary>
        public static string HelpTextStudyPerformer {
            get {
                return ResourceManager.GetString("HelpTextStudyPerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите юридический адрес компании которая проводит клиническое исследование.
        /// </summary>
        public static string HelpTextStudyPerformerRegisteredAddress {
            get {
                return ResourceManager.GetString("HelpTextStudyPerformerRegisteredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите фактический адрес компании которая проводит клиническое исследование.
        /// </summary>
        public static string HelpTextStudyPerformerStatutoryAddress {
            get {
                return ResourceManager.GetString("HelpTextStudyPerformerStatutoryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите фазу клинического исследования, которое должно получить одобрение этического комитета.
        /// </summary>
        public static string HelpTextStudyPhase {
            get {
                return ResourceManager.GetString("HelpTextStudyPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите планируемую дату окончания исследования.
        /// </summary>
        public static string HelpTextStudyPlannedEndDate {
            get {
                return ResourceManager.GetString("HelpTextStudyPlannedEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите планируемую дату начала исследования.
        /// </summary>
        public static string HelpTextStudyPlannedStartDate {
            get {
                return ResourceManager.GetString("HelpTextStudyPlannedStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите название компании которая является производителем или упаковщиком медицинского препарата, для которого производится исследование.
        /// </summary>
        public static string HelpTextStudyProducer {
            get {
                return ResourceManager.GetString("HelpTextStudyProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите название компании, которая является спонсором проводимого клинического исследования.
        /// </summary>
        public static string HelpTextStudySponsor {
            get {
                return ResourceManager.GetString("HelpTextStudySponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите тип проводимого исследования.
        /// </summary>
        public static string HelpTextStudyType {
            get {
                return ResourceManager.GetString("HelpTextStudyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите название исследования, по которому вы хотите отправить заявку.
        /// </summary>
        public static string HelpTextTitle {
            get {
                return ResourceManager.GetString("HelpTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите подход к терапии лечения.
        /// </summary>
        public static string HelpTherapyDescription {
            get {
                return ResourceManager.GetString("HelpTherapyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я согласен с.
        /// </summary>
        public static string IAccept {
            get {
                return ResourceManager.GetString("IAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неудачная попытка входа..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный код..
        /// </summary>
        public static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка локализации {0}. Не удается найти свойство {2} у типа {1}.
        /// </summary>
        public static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокировано..
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация завершена успешно. Дождитесь активации вашей учетной записи администратором.
        /// </summary>
        public static string MailRegistrationSuccessfulBody {
            get {
                return ResourceManager.GetString("MailRegistrationSuccessfulBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация завершена успешно.
        /// </summary>
        public static string MailRegistrationSuccessfulSubject {
            get {
                return ResourceManager.GetString("MailRegistrationSuccessfulSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты совещания.
        /// </summary>
        public static string MeetingNotes {
            get {
                return ResourceManager.GetString("MeetingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Совещание по заявке - .
        /// </summary>
        public static string MeetingRoom {
            get {
                return ResourceManager.GetString("MeetingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на След..
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (не отвечайте).
        /// </summary>
        public static string NoReplyName {
            get {
                return ResourceManager.GetString("NoReplyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для данной заявки не было загружено ни одного документа.
        /// </summary>
        public static string NoSubmissionForRequest {
            get {
                return ResourceManager.GetString("NoSubmissionForRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указано.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не достаточно документации для отправки в этический комитет.
        /// </summary>
        public static string NotSufficientDocumentationForSubmission {
            get {
                return ResourceManager.GetString("NotSufficientDocumentationForSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О нас.
        /// </summary>
        public static string PageAboutTitle {
            get {
                return ResourceManager.GetString("PageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все заявки.
        /// </summary>
        public static string PageAllRequestsTitle {
            get {
                return ResourceManager.GetString("PageAllRequestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все пользователи.
        /// </summary>
        public static string PageAllUsersTitle {
            get {
                return ResourceManager.GetString("PageAllUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол изменений.
        /// </summary>
        public static string PageAuditLogTitle {
            get {
                return ResourceManager.GetString("PageAuditLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма изменения пароля.
        /// </summary>
        public static string PageChangePasswordForm {
            get {
                return ResourceManager.GetString("PageChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение пароля.
        /// </summary>
        public static string PageChangePasswordTitle {
            get {
                return ResourceManager.GetString("PageChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты.
        /// </summary>
        public static string PageClientsTitle {
            get {
                return ResourceManager.GetString("PageClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комитеты.
        /// </summary>
        public static string PageCommitteesTitle {
            get {
                return ResourceManager.GetString("PageCommitteesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы успешно подтвердили ваш e-mail..
        /// </summary>
        public static string PageConfirmEmailBody {
            get {
                return ResourceManager.GetString("PageConfirmEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение e-mail.
        /// </summary>
        public static string PageConfirmEmailTitle {
            get {
                return ResourceManager.GetString("PageConfirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наш офис.
        /// </summary>
        public static string PageContactsAddress {
            get {
                return ResourceManager.GetString("PageContactsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Санкт-Петербург,.
        /// </summary>
        public static string PageContactsAddressLine1 {
            get {
                return ResourceManager.GetString("PageContactsAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пл. Конституции, дом 7, литера А. офис №413.
        /// </summary>
        public static string PageContactsAddressLine2 {
            get {
                return ResourceManager.GetString("PageContactsAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string PageContactsContactsEmail {
            get {
                return ResourceManager.GetString("PageContactsContactsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string PageContactsContactsPhone {
            get {
                return ResourceManager.GetString("PageContactsContactsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тел.
        /// </summary>
        public static string PageContactsContactsPhoneAbbr {
            get {
                return ResourceManager.GetString("PageContactsContactsPhoneAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skype.
        /// </summary>
        public static string PageContactsContactsSkype {
            get {
                return ResourceManager.GetString("PageContactsContactsSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LEC-Online - это профессиональный межрегиональный мультидисциплинарный этический комитет, впервые в РФ использующий современные сертифицированные технологии связи и документооборота для обеспечения быстрого и качественного процесса этической экспертизы.
        /// </summary>
        public static string PageContactsInfoLine1 {
            get {
                return ResourceManager.GetString("PageContactsInfoLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете обратиться к нам по телефону, по электронной почте или договориться о встрече в нашем офисе. Будем рады помочь вам и ответить на все ваши вопросы..
        /// </summary>
        public static string PageContactsInfoLine2 {
            get {
                return ResourceManager.GetString("PageContactsInfoLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string PageContactsTitle {
            get {
                return ResourceManager.GetString("PageContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кабинет.
        /// </summary>
        public static string PageDashboardTitle {
            get {
                return ResourceManager.GetString("PageDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string PageError {
            get {
                return ResourceManager.GetString("PageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Во время обработки вашего запроса произошла ошибка..
        /// </summary>
        public static string PageErrorDescription {
            get {
                return ResourceManager.GetString("PageErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка..
        /// </summary>
        public static string PageErrorHeader {
            get {
                return ResourceManager.GetString("PageErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки.
        /// </summary>
        public static string PageErrorsTitle {
            get {
                return ResourceManager.GetString("PageErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы успешно восстановили свой пароль..
        /// </summary>
        public static string PageForgotPasswordConfirmationCaption {
            get {
                return ResourceManager.GetString("PageForgotPasswordConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешное восстановление пароля.
        /// </summary>
        public static string PageForgotPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("PageForgotPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забыли пароль?.
        /// </summary>
        public static string PageForgotPasswordTitle {
            get {
                return ResourceManager.GetString("PageForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        public static string PageHomeTitle {
            get {
                return ResourceManager.GetString("PageHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установка.
        /// </summary>
        public static string PageInstallationTitle {
            get {
                return ResourceManager.GetString("PageInstallationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокировано.
        /// </summary>
        public static string PageLockedOutTitle {
            get {
                return ResourceManager.GetString("PageLockedOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        public static string PageLoginTitle {
            get {
                return ResourceManager.GetString("PageLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измените параметры вашей учетной записи.
        /// </summary>
        public static string PageManageAccountForm {
            get {
                return ResourceManager.GetString("PageManageAccountForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление аккаунтом.
        /// </summary>
        public static string PageManageAccountTitle {
            get {
                return ResourceManager.GetString("PageManageAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неподтвержденные пользователи.
        /// </summary>
        public static string PageNotConfirmedUsersTitle {
            get {
                return ResourceManager.GetString("PageNotConfirmedUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявки.
        /// </summary>
        public static string PageRequestsTitle {
            get {
                return ResourceManager.GetString("PageRequestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешный сброс пароля.
        /// </summary>
        public static string PageResetPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("PageResetPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс пароля.
        /// </summary>
        public static string PageResetPasswordTitle {
            get {
                return ResourceManager.GetString("PageResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string PageUserProfileTitle {
            get {
                return ResourceManager.GetString("PageUserProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string PageUsersTitle {
            get {
                return ResourceManager.GetString("PageUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш пароль был изменен..
        /// </summary>
        public static string PasswordChangedConfirmation {
            get {
                return ResourceManager.GetString("PasswordChangedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста перейдтие на .
        /// </summary>
        public static string PleaseClickHere {
            get {
                return ResourceManager.GetString("PleaseClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перед загрузкой постарайтесь указывать понятное имя файла, чтобы сотрудникам комитета было удобнее с ними работать.
        /// </summary>
        public static string PleaseSpecifyMeaningfulFleName {
            get {
                return ResourceManager.GetString("PleaseSpecifyMeaningfulFleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пред..
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрируйте учетную запись:.
        /// </summary>
        public static string RegisterANewAccount {
            get {
                return ResourceManager.GetString("RegisterANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация завершена успешно. Дождитесь активации вашей учетной записи администратором.
        /// </summary>
        public static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отклонить заявку.
        /// </summary>
        public static string RejectApplication {
            get {
                return ResourceManager.GetString("RejectApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Убрать файл.
        /// </summary>
        public static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доп. вложения.
        /// </summary>
        public static string RequestAdditionalFormDocumentation {
            get {
                return ResourceManager.GetString("RequestAdditionalFormDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необязательные вложения к документации.
        /// </summary>
        public static string RequestAdditionalFormDocumentationHint {
            get {
                return ResourceManager.GetString("RequestAdditionalFormDocumentationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на События.
        /// </summary>
        public static string RequestFormActions {
            get {
                return ResourceManager.GetString("RequestFormActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на События и операции связанные с этой заявкой.
        /// </summary>
        public static string RequestFormActionsHint {
            get {
                return ResourceManager.GetString("RequestFormActionsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Базовая информация.
        /// </summary>
        public static string RequestFormBaseInformation {
            get {
                return ResourceManager.GetString("RequestFormBaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основная информация о заявке.
        /// </summary>
        public static string RequestFormBaseInformationHint {
            get {
                return ResourceManager.GetString("RequestFormBaseInformationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактное лицо.
        /// </summary>
        public static string RequestFormContactInformation {
            get {
                return ResourceManager.GetString("RequestFormContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные об административном контакте.
        /// </summary>
        public static string RequestFormContactInformationHint {
            get {
                return ResourceManager.GetString("RequestFormContactInformationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вложения.
        /// </summary>
        public static string RequestFormDocumentation {
            get {
                return ResourceManager.GetString("RequestFormDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на файлы и документация прилагающаяся к заявке.
        /// </summary>
        public static string RequestFormDocumentationHint {
            get {
                return ResourceManager.GetString("RequestFormDocumentationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество пациентов в РФ.
        /// </summary>
        public static string RequestPatientsCount {
            get {
                return ResourceManager.GetString("RequestPatientsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите ваш новый пароль.
        /// </summary>
        public static string ResetPasswordCaption {
            get {
                return ResourceManager.GetString("ResetPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы успешно сбросили пароль..
        /// </summary>
        public static string ResetPasswordConfirmationCaption {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке файла.
        /// </summary>
        public static string ResponseError {
            get {
                return ResourceManager.GetString("ResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ваш email и получите инструкции по восстановлению вашего пароля..
        /// </summary>
        public static string RetreivePasswordInstructions {
            get {
                return ResourceManager.GetString("RetreivePasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление пароля.
        /// </summary>
        public static string RetrievePassword {
            get {
                return ResourceManager.GetString("RetrievePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отозвать заявку.
        /// </summary>
        public static string RevokeApplication {
            get {
                return ResourceManager.GetString("RevokeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string RoleAdministrator {
            get {
                return ResourceManager.GetString("RoleAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Член этического комитета.
        /// </summary>
        public static string RoleEthicalCommitteeMember {
            get {
                return ResourceManager.GetString("RoleEthicalCommitteeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер.
        /// </summary>
        public static string RoleManager {
            get {
                return ResourceManager.GetString("RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудник Мед. центра.
        /// </summary>
        public static string RoleMedicalCenter {
            get {
                return ResourceManager.GetString("RoleMedicalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файлы для загрузки.
        /// </summary>
        public static string SelectFilesToUpload {
            get {
                return ResourceManager.GetString("SelectFilesToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string SendMe {
            get {
                return ResourceManager.GetString("SendMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначить совещание.
        /// </summary>
        public static string SetMeeting {
            get {
                return ResourceManager.GetString("SetMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывается c {0} по {1} записи. Всего {2} записей..
        /// </summary>
        public static string ShowingEntries {
            get {
                return ResourceManager.GetString("ShowingEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период прохождения исследования.
        /// </summary>
        public static string StudyDurationData {
            get {
                return ResourceManager.GetString("StudyDurationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организационные данные.
        /// </summary>
        public static string StudyLegalData {
            get {
                return ResourceManager.GetString("StudyLegalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технические данные по исследованию.
        /// </summary>
        public static string StudyTechnicalData {
            get {
                return ResourceManager.GetString("StudyTechnicalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка-{0}.zip.
        /// </summary>
        public static string SubmissionBaseFileName {
            get {
                return ResourceManager.GetString("SubmissionBaseFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить заявку.
        /// </summary>
        public static string SubmitRequest {
            get {
                return ResourceManager.GetString("SubmitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на страницу входа.
        /// </summary>
        public static string ToLogin {
            get {
                return ResourceManager.GetString("ToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двух-факторная аутентификация не настроена.
        /// </summary>
        public static string TwoFactorAuthenticationNotConfigured {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить документацию.
        /// </summary>
        public static string UploadDocumentation {
            get {
                return ResourceManager.GetString("UploadDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить файлы.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете загрузить необходимые файлы, на странице редактирования, после того как заполните базовую информацию о заявке..
        /// </summary>
        public static string UploadingIsAvailableOnEditPage {
            get {
                return ResourceManager.GetString("UploadingIsAvailableOnEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользовательское соглашение.
        /// </summary>
        public static string UserAgreement {
            get {
                return ResourceManager.GetString("UserAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользовательским соглашением.
        /// </summary>
        public static string UserAgreementAccepts {
            get {
                return ResourceManager.GetString("UserAgreementAccepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключен.
        /// </summary>
        public static string UserStatusDisabled {
            get {
                return ResourceManager.GetString("UserStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрирован.
        /// </summary>
        public static string UserStatusRegistered {
            get {
                return ResourceManager.GetString("UserStatusRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидает подтверждения.
        /// </summary>
        public static string UserStatusWaitingApproval {
            get {
                return ResourceManager.GetString("UserStatusWaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль и подтверждение пароля отличаются.
        /// </summary>
        public static string ValidationMessageCompare {
            get {
                return ResourceManager.GetString("ValidationMessageCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя указать больше одной роли.
        /// </summary>
        public static string ValidationMessageCouldNotHaveMoreThenOneRole {
            get {
                return ResourceManager.GetString("ValidationMessageCouldNotHaveMoreThenOneRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не может быть одновременно в организации и этическом комитете.
        /// </summary>
        public static string ValidationMessageCouldNotSetBothClientAndCommittee {
            get {
                return ResourceManager.GetString("ValidationMessageCouldNotSetBothClientAndCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле {0} не является e-mail адресом.
        /// </summary>
        public static string ValidationMessageEmailAddress {
            get {
                return ResourceManager.GetString("ValidationMessageEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь должен принять пользовательское соглашение.
        /// </summary>
        public static string ValidationMessageLicenseAgreementNotAccepted {
            get {
                return ResourceManager.GetString("ValidationMessageLicenseAgreementNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле {0} должно быть в диапазоне от {1} до {2}..
        /// </summary>
        public static string ValidationMessageRange {
            get {
                return ResourceManager.GetString("ValidationMessageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле {0} обязательно к заполнению..
        /// </summary>
        public static string ValidationMessageRequired {
            get {
                return ResourceManager.GetString("ValidationMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо принять решение.
        /// </summary>
        public static string ValidationMessageResolutionRequired {
            get {
                return ResourceManager.GetString("ValidationMessageResolutionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо чтобы пользователь был хотя бы в одной роли.
        /// </summary>
        public static string ValidationMessageShouldHaveAtLeastOneRole {
            get {
                return ResourceManager.GetString("ValidationMessageShouldHaveAtLeastOneRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} должен быть {2} символов в длину..
        /// </summary>
        public static string ValidationMessageStringLength {
            get {
                return ResourceManager.GetString("ValidationMessageStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать комитет, куда будет отправляться заявка на рассмотрение.
        /// </summary>
        public static string ValidationMessageSubmissionCommitteeRequired {
            get {
                return ResourceManager.GetString("ValidationMessageSubmissionCommitteeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участники комитета для заявки.
        /// </summary>
        public static string ViewAttendees {
            get {
                return ResourceManager.GetString("ViewAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр записи аудита №.
        /// </summary>
        public static string ViewChangeLogEntry {
            get {
                return ResourceManager.GetString("ViewChangeLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр заявки.
        /// </summary>
        public static string ViewRequest {
            get {
                return ResourceManager.GetString("ViewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Согласен.
        /// </summary>
        public static string VoteAccept {
            get {
                return ResourceManager.GetString("VoteAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не согласен.
        /// </summary>
        public static string VoteReject {
            get {
                return ResourceManager.GetString("VoteReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать,.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже проголосовали.
        /// </summary>
        public static string YouAlreadyPlaceVote {
            get {
                return ResourceManager.GetString("YouAlreadyPlaceVote", resourceCulture);
            }
        }
    }
}
